name: Test PyPI Deployment (Monthly)


on: [pull_request]
#  schedule:
#    - cron: "0 0 6 * *"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Retrieve current YYYY_MM
        run: |
          echo "YYYY_MM=$(date +'%Y_%m')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install osu-data-csv==0.1.5

      - name: Attempt to use and convert files
        run: |
          osu-data-csv \
            -y "${YYYY_MM}" \
            -d "mania" \
            -s "1000" \
            -l "data/" \
            -c "N" \
            -q "Y"
